/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controleestoque.Views;
import controleestoque.Controllers.ProdutoController;
import controleestoque.Controllers.ClienteController;
import controleestoque.Controllers.FornecedorController;
import controleestoque.Controllers.CategoriaController;
import controleestoque.Controllers.TipoController;
import controleestoque.Models.Produto;
import controleestoque.Models.Cliente;
import controleestoque.Models.Categoria;
import  controleestoque.Models.Fornecedor;
import controleestoque.Models.TipoProduto;
import controleestoque.Views.ProdutoView;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilhermemarques
 */
public class FormOrigemView extends javax.swing.JFrame {

        ProdutoController produtoController = new ProdutoController();
        ClienteController clienteController = new ClienteController();
        FornecedorController fornecedorController = new FornecedorController();

    /**
     * Creates new form FormOrigemView
     */
    public FormOrigemView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
        public void ConsultarProdutos(){
        ArrayList<Produto> produtos = new ArrayList<Produto>();
        try {
            produtos = produtoController.Consultar();
            for (Produto produto : produtos){
                dpdProduto.addItem(produto.getNome());
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormOrigemView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
        public void CarregarOrigem(){
            if (rbtnCliente.isSelected()==false && rbtnFornecedor.isSelected()==false) {
                lblNomeCliente.setVisible(false);
                dpdCliente.setVisible(false);
                lblNomeFornecedor.setVisible(false);
                dpdFornecedor.setVisible(false);                
            }
            
            try {
            ArrayList<Cliente> clientes = new ArrayList<Cliente>();
            clientes = clienteController.Consultar();
            for (Cliente cliente : clientes){
                dpdCliente.addItem(cliente.getNome());
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormOrigemView.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                    ArrayList<Fornecedor> fornecedores = new ArrayList<Fornecedor>();
                    fornecedores = fornecedorController.Consultar();
                    for (Fornecedor fornecedor : fornecedores) {
                        dpdFornecedor.addItem(fornecedor.getNome());                        
                    }
        } catch (SQLException ex) {
            Logger.getLogger(FormOrigemView.class.getName()).log(Level.SEVERE, null, ex);
        }    
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOrigem = new javax.swing.ButtonGroup();
        lblDescricao = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblProduto = new javax.swing.JLabel();
        dpdProduto = new javax.swing.JComboBox<>();
        btnProduto = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblOrigem = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        lblNomeCliente = new javax.swing.JLabel();
        rbtnFornecedor = new javax.swing.JRadioButton();
        rbtnCliente = new javax.swing.JRadioButton();
        dpdCliente = new javax.swing.JComboBox<>();
        lblPreco2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        dpdFornecedor = new javax.swing.JComboBox<>();
        lblNomeFornecedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblDescricao.setText("Total");

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastrar Entrada");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProduto.setText("Produto");

        dpdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpdProdutoActionPerformed(evt);
            }
        });

        btnProduto.setText("+");
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        lblNome.setText("Quantidade");

        lblOrigem.setText("Origem");

        txtNome.setMinimumSize(new java.awt.Dimension(11, 30));

        lblData.setText("Data");

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        lblNomeCliente.setText("Nome");

        buttonGroupOrigem.add(rbtnFornecedor);
        rbtnFornecedor.setText("Fornecedor");
        rbtnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFornecedorActionPerformed(evt);
            }
        });

        buttonGroupOrigem.add(rbtnCliente);
        rbtnCliente.setText("Cliente");
        rbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnClienteActionPerformed(evt);
            }
        });

        dpdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpdClienteActionPerformed(evt);
            }
        });

        lblPreco2.setText("R$");

        dpdFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpdFornecedorActionPerformed(evt);
            }
        });

        lblNomeFornecedor.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblData)
                        .addGap(18, 18, 18)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreco2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProduto)
                        .addGap(2, 2, 2)
                        .addComponent(dpdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dpdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrigem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnFornecedor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dpdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(dpdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigem)
                    .addComponent(rbtnFornecedor)
                    .addComponent(rbtnCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomeCliente)
                        .addComponent(dpdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomeFornecedor)
                        .addComponent(dpdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(lblPreco2)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Produto produto = new Produto();

        if(!isEditing) {
            try {
                produto.setCategoria(new Categoria(dpdProduto.getSelectedItem().toString()));
                produto.setTipoProduto(new TipoProduto(dpdCliente.getSelectedItem().toString()));
                produto.setNome(txtNome.getText());
                produto.setDescricao(txtDescricao.getText());
                produto.setPreco(Double.parseDouble(txtPreco.getText()));

                produtoController.Salvar(produto);

                this.setVisible(false);
                produtoView.ConsultarProdutos();

            } catch (SQLException ex) {
                Logger.getLogger(FormProdutoView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                this.produtoEdit.setCategoria(new Categoria(dpdProduto.getSelectedItem().toString()));
                this.produtoEdit.setTipoProduto(new TipoProduto(dpdCliente.getSelectedItem().toString()));
                this.produtoEdit.setNome(txtNome.getText());
                this.produtoEdit.setDescricao(txtDescricao.getText());
                this.produtoEdit.setPreco(Double.parseDouble(txtPreco.getText()));

                produtoController.Editar(this.produtoEdit);

                this.setVisible(false);
                produtoView.ConsultarProdutos();

            } catch (SQLException ex) {
                Logger.getLogger(FormProdutoView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void dpdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpdProdutoActionPerformed

    }//GEN-LAST:event_dpdProdutoActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        FormProdutoView formProduto = new FormProdutoView();
        formProduto.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void dpdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpdClienteActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       CarregarOrigem();
       ConsultarProdutos();
    }//GEN-LAST:event_formWindowOpened

    private void dpdFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpdFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpdFornecedorActionPerformed

    private void rbtnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFornecedorActionPerformed
            if (rbtnFornecedor.isSelected()) {
                lblNomeCliente.setVisible(false);
                dpdCliente.setVisible(false);
                lblNomeFornecedor.setVisible(true);
                dpdFornecedor.setVisible(true);
            }    }//GEN-LAST:event_rbtnFornecedorActionPerformed

    private void rbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnClienteActionPerformed
            if (rbtnCliente.isSelected()) {
                lblNomeFornecedor.setVisible(false);
                dpdFornecedor.setVisible(false);
                lblNomeCliente.setVisible(true);
                dpdCliente.setVisible(true);

            }    }//GEN-LAST:event_rbtnClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOrigemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOrigemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOrigemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOrigemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOrigemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroupOrigem;
    private javax.swing.JComboBox<String> dpdCliente;
    private javax.swing.JComboBox<String> dpdFornecedor;
    private javax.swing.JComboBox<String> dpdProduto;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeFornecedor;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblPreco2;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnCliente;
    private javax.swing.JRadioButton rbtnFornecedor;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
